services:
  lcd-remote-app:
    init: true
    image: ghcr.io/astral-sh/uv:python3.13-bookworm
    container_name: lcd-remote-app
    ports:
      - "80:8000"
    volumes:
      - .:/app
      - venv_cache:/app/.venv
      - /app/.git
      - /usr/share/fonts:/usr/share/fonts:ro
    working_dir: /app
    #command: uv run uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    command: uv run uvicorn main:app --host 0.0.0.0 --port 8000
    restart: always
    privileged: true
    devices:
      - /dev/spidev0.0:/dev/spidev0.0
      - /dev/gpiomem:/dev/gpiomem

volumes:
  venv_cache:
