[project]
name = "lcd-remote-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.119.1",
    "jinja2>=3.1.6",
    "smbus2>=0.5.0",
    "uvicorn>=0.38.0",
]
